web-eid/web-eid-webextension

src/background/actions/TokenSigning/getCertificate.ts
src/background/actions/sign.ts
src/models/NativeAppMessage.ts

Resolves WE2-489
Relates to https://github.com/web-eid/web-eid-app/pull/86 changes

feat: change native app command get-certificate sign/auth to get-signing-certificate

---

static/chrome/manifest.json
static/firefox/manifest.json
static/safari/manifest.json

fix(manifest): update extension description for all stores

---

src/background-safari/services/NativeAppService.ts
src/background/actions/TokenSigning/errorToResponse.ts
src/background/actions/TokenSigning/getCertificate.ts
src/background/actions/TokenSigning/getStatus.ts
src/background/actions/TokenSigning/index.ts
src/background/actions/TokenSigning/sign.ts
src/background/actions/authenticate.ts
src/background/actions/getStatus.ts
src/background/actions/sign.ts
src/background/background.ts
src/background/services/NativeAppService.ts
src/background/services/WebServerService.ts
src/config.ts
src/content/content.ts
src/models/AwaitingResponseMap.ts
src/models/Browser.ts
src/models/Browser/Permissions.ts
src/models/Browser/Runtime.ts
src/models/Browser/WebRequest.ts
src/models/HttpResponse.ts
src/models/LibraryMessage.ts
src/models/StatusOptions.ts
src/models/TokenSigning/TokenSigningMessage.ts
src/models/TokenSigning/TokenSigningPromise.ts
src/models/TokenSigning/TokenSigningResponse.ts
src/models/TokenSigning/TokenSigningType.ts
src/models/TypedMap.ts
src/shared/ByteArray.ts
src/shared/tokenSigningResponse.ts
src/shared/utils.ts

Update copyright year

---

package-lock.json
package.json
src/background/actions/authenticate.ts
src/background/actions/sign.ts
src/background/background.ts
src/background/services/WebServerService.ts
src/content/TokenSigning/injectPageScript.ts
src/content/TokenSigning/pageScript.ts
src/content/content.ts
src/models/Browser.ts
src/models/Browser/Runtime.ts
src/models/Browser/Tabs.ts
static/safari/manifest.json

* Fetch is now done in content script
* Moved TokenSigning script to separate files to clean up content.ts

fix: fetch fails in Safari 14 as requests from background script are considered as CORS

---

.github/workflows/build.yml
jest.config.js
package-lock.json
package.json
scripts/build.mjs
src/background/actions/status.ts
src/background/background.ts
src/content/content.ts
src/shared/utils/__tests__/version-test.ts
src/shared/utils/checkCompatibility.ts
src/shared/utils/semver.ts
tsconfig.json

Version checking was removed from the library and added to the extension side for greater flexibility
Contains changes from #21

feat: version checking added to extension

---

rollup.config.js

Fix Safari backwards compatibility option

---

package-lock.json
package.json
static/chrome/manifest.json
static/firefox/manifest.json
static/safari/manifest.json

fix(manifest): activate Web eID backwards-compatible mode in iframes

---

src/background/background.ts
src/models/Browser.ts
src/models/Browser/PKCS11.ts

Remove PKCS11 module from Firefox

---

package-lock.json
package.json
src/background/background.ts
src/background/services/Pkcs11Service.ts
static/firefox/manifest.json

Resolves WE2-664
Version bump to 2.2.0

feat: Automatic removal of OpenEID PKCS#11 modules

---

package-lock.json
package.json
scripts/build.mjs
src/background/background.ts
src/models/Browser/Runtime.ts
src/models/Browser/Tabs.ts
static/_locales/en/messages.json
static/_locales/et/messages.json
static/_locales/ru/messages.json
static/firefox/manifest.json
static/firefox/manifest_v3.json
static/views/installed.html
static/views/installed.js

Create consent page

---

package.json

Update version number 2.2.1

---

.github/workflows/codeql.yml
src/content/content.ts

Add CodeQL Action

---

.github/workflows/build.yml

Add Coverity static analyzer scan

---

package-lock.json
package.json
rollup.config.js

Polyfill is still needed in chrome

---

src/background/services/NativeAppService.ts

Defer active connection cleanup

---

static/safari/manifest.json
static/safari/manifest_v3.json

Remove unused tabs permission

---

src/background/actions/TokenSigning/threeLetterLanguageCodes.ts
static/_locales/cs/messages.json
static/_locales/sk/messages.json

Signed-off-by: Martin Mayer <martin.kelly.mayer@gmail.com>

CZ and SK localization

---

rollup.config.js

Add polyfill only to chrome extension

---

package-lock.json
package.json

Update version number to 2.3.0

---

static/safari/manifest.json
static/safari/manifest_v3.json

WE2-1061
Signed-off-by: Sven Mitt <svenzik@users.noreply.github.com>

We have not found default_locale" in the folder "_locales"
